### ISSUE TITLE
unable to share secrets

### ISSUE THREAD

**Issue by a-net** [marius-wieschollek/passwords#225]
When trying to share a password, the selected shared user name icon just keeps spinning. The share is not completed. Using nextcloud: 17.0.1. Installed the app from within nextcloud. I also ran the updater to 17.0.2, which updated all installed apps, but still the same issue persists.

The app installed are:
    Brute-force settings ↗
    Calendar ↗
    Contacts ↗
    Deck ↗
    Notifications for calendar event updates ↗
    File access control ↗
    Antivirus for files ↗
    Files automated tagging ↗
    Mind Map ↗
    Mail ↗
    Passwords ↗
    Ransomware protection ↗
    Talk ↗
    Terms of service ↗

*Nextcloud was installed from within cPanel via Softaculous.

**Comment by marius-wieschollek** [comment]
Hi. Can you please fill out the [bug report form](https://raw.githubusercontent.com/marius-wieschollek/passwords/master/.github/ISSUE_TEMPLATE/Bug_report.md) and paste it here?

**Comment by a-net** [comment]
---

name: Bug Report

about: Report a functional error in the app. If you need assistance with your setup or have questions please go to our forum.

labels: bug

---

 



 

 

### System Information

- Nextcloud Version: 17.0.2

- PHP Version: 7.3

- Passwords Version: 2020.1.0

- Browser and Version: Firefox 71.0

- Client OS and Version: Windows 8.1 Pro

- Server OS and Version: CentOS 7.7 / WHM/cPanel v84.0.18

 

### Steps to reproduce

1. 

I created a password and then go to the share feature. When entering a contact name, the name is found in the search and I click it. The contact then shows up below the ‘search user’ field but the user icon keeps spinning indefinitely.

2. 
*screenshot & image attached of spinning contact icon.


3. 

 

### Actual result

What does happen?

I am unable to share the secret with the other user. I have logged in as the other user to test.

 

### Expected result

What should happen?

I expect that the spinning icon for the shared user should stop spinning to indicate the share was successful. The shared with user should see the password in their profile.

 

### Nextcloud log

<details>

<summary>Nextcloud log – not enabled. Can enable later. </summary>

 

```

See Settings > Log  (Copy Raw)

```

</details>

 

### Browser log

<details>

<summary>Browser log</summary>

 

```



 


<div id="terms_of_service_confirm"><!----></div>
	<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>

		
		<a href="#app-content" class="button primary skip-navigation skip-content">Skip to main content</a>
		<a href="#app-navigation" class="button primary skip-navigation">Skip to navigation of app</a>

		<div id="notification-container">
			<div id="notification"></div>
		</div>
		<header role="banner" id="header">
			<div class="header-left">
				<a href="/cloud/index.php" id="nextcloud">
					<div class="logo logo-icon">
						<h1 class="hidden-visually">
							Nextcloud Passwords						</h1>
					</div>
				</a>

				<ul id="appmenu">
											<li data-id="files" class="" tabindex="-1" style="">
							<a href="/cloud/index.php/apps/files/" aria-label="Files">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/files/img/app.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Files								</span>
							</a>
						</li>
											<li data-id="activity" class="" tabindex="-1">
							<a href="/cloud/index.php/apps/activity/" aria-label="Activity">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/activity/img/activity.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Activity								</span>
							</a>
						</li>
											<li data-id="gallery" class="" tabindex="-1">
							<a href="/cloud/index.php/apps/gallery/" aria-label="Gallery">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/gallery/img/app.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Gallery								</span>
							</a>
						</li>
											<li data-id="spreed" class="" tabindex="-1">
							<a href="https://sample-domain/cloud/index.php/apps/spreed/" aria-label="Talk">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/spreed/img/app.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Talk								</span>
							</a>
						</li>
											<li data-id="mail" class="" tabindex="-1">
							<a href="/cloud/index.php/apps/mail/" aria-label="Mail">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/mail/img/mail.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Mail								</span>
							</a>
						</li>
											<li data-id="contacts" class="" tabindex="-1">
							<a href="/cloud/index.php/apps/contacts/" aria-label="Contacts">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/contacts/img/app.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Contacts								</span>
							</a>
						</li>
											<li data-id="calendar" class="hidden" tabindex="-1">
							<a href="/cloud/index.php/apps/calendar/" aria-label="Calendar">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/calendar/img/calendar.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Calendar								</span>
							</a>
						</li>
											<li data-id="deck" class="hidden" tabindex="-1">
							<a href="/cloud/index.php/apps/deck/" aria-label="Deck">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/deck/img/deck.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Deck								</span>
							</a>
						</li>
											<li data-id="passwords" class="" tabindex="-1">
							<a href="/cloud/index.php/apps/passwords/" class="active" aria-label="Passwords">
									<svg width="20" height="20" viewBox="0 0 20 20" alt="">
																				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/cloud/apps/passwords/img/app.svg?v=d1f5d314" class="app-icon"></image>
									</svg>
								<span>
									Passwords								</span>
							</a>
						</li>
										<li id="more-apps" class="menutoggle" aria-haspopup="true" aria-controls="navigation" aria-expanded="false">
						<a href="#" aria-label="More apps">
							<div class="icon-more-white"></div>
							<span>More</span>
						</a>
					</li>
				</ul>

				<nav role="navigation">
					<div id="navigation" style="display: none;" aria-label="More apps menu" class="menu">
						<div id="apps">
							<ul>
																	<li data-id="files" class="in-header">
									<a href="/cloud/index.php/apps/files/" aria-label="Files">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-files"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-files)" xlink:href="/cloud/apps/files/img/app.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Files</span>
									</a>
									</li>
																	<li data-id="activity" class="in-header">
									<a href="/cloud/index.php/apps/activity/" aria-label="Activity">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-activity"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-activity)" xlink:href="/cloud/apps/activity/img/activity.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Activity</span>
									</a>
									</li>
																	<li data-id="gallery" class="in-header">
									<a href="/cloud/index.php/apps/gallery/" aria-label="Gallery">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-gallery"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-gallery)" xlink:href="/cloud/apps/gallery/img/app.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Gallery</span>
									</a>
									</li>
																	<li data-id="spreed" class="in-header">
									<a href="https://sample-domain/cloud/index.php/apps/spreed/" aria-label="Talk">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-spreed"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-spreed)" xlink:href="/cloud/apps/spreed/img/app.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Talk</span>
									</a>
									</li>
																	<li data-id="mail" class="in-header">
									<a href="/cloud/index.php/apps/mail/" aria-label="Mail">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-mail"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-mail)" xlink:href="/cloud/apps/mail/img/mail.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Mail</span>
									</a>
									</li>
																	<li data-id="contacts" class="in-header">
									<a href="/cloud/index.php/apps/contacts/" aria-label="Contacts">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-contacts"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-contacts)" xlink:href="/cloud/apps/contacts/img/app.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Contacts</span>
									</a>
									</li>
																	<li data-id="calendar" class="">
									<a href="/cloud/index.php/apps/calendar/" aria-label="Calendar">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-calendar"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-calendar)" xlink:href="/cloud/apps/calendar/img/calendar.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Calendar</span>
									</a>
									</li>
																	<li data-id="deck">
									<a href="/cloud/index.php/apps/deck/" aria-label="Deck">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-deck"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-deck)" xlink:href="/cloud/apps/deck/img/deck.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Deck</span>
									</a>
									</li>
																	<li data-id="passwords" class="in-header">
									<a href="/cloud/index.php/apps/passwords/" class="active" aria-label="Passwords">
										<svg width="16" height="16" viewBox="0 0 16 16" alt="">
											<defs><filter id="invertMenuMore-passwords"><feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix></filter></defs>
											<image x="0" y="0" width="16" height="16" preserveAspectRatio="xMinYMin meet" filter="url(#invertMenuMore-passwords)" xlink:href="/cloud/apps/passwords/img/app.svg?v=d1f5d314" class="app-icon"></image>
										</svg>
										<span>Passwords</span>
									</a>
									</li>
															</ul>
						</div>
					</div>
				</nav>

			</div>

			<div class="header-right">
				<form class="searchbox" action="#" method="post" role="search" novalidate="" style="opacity: 1;">
					<label for="searchbox" class="hidden-visually">
						Search					</label>
					<input id="searchbox" type="search" name="query" value="" required="" class="hidden icon-search-white icon-search-force-white" autocomplete="off" style="display: block;">
					<button class="icon-close-white" type="reset"><span class="hidden-visually">Reset search</span></button>
				</form><div data-v-42208770="" class="notifications"><div data-v-42208770="" tabindex="0" role="button" aria-label="t('notifications', 'Notifications')" aria-haspopup="true" aria-controls="notification-container" aria-expanded="false" class="notifications-button menutoggle"><img data-v-42208770="" alt="" title="Notifications" src="/cloud/apps/notifications/img/notifications.svg" class="svg"></div> <div data-v-42208770="" class="notification-container menu"><div data-v-42208770="" class="emptycontent"><div data-v-42208770="" class="icon icon-notifications-dark"></div> <h2 data-v-42208770="">No notifications</h2></div></div></div>
				<div id="contactsmenu">
					<div class="icon-contacts menutoggle" tabindex="0" role="button" aria-haspopup="true" aria-controls="contactsmenu-menu" aria-expanded="false">
						<span class="hidden-visually">Contacts</span>
					</div>
					<div id="contactsmenu-menu" class="menu" aria-label="Contacts menu"></div>
				</div>
				<div id="settings">
					<div id="expand" tabindex="0" role="button" class="menutoggle" aria-label="Settings" aria-haspopup="true" aria-controls="expanddiv" aria-expanded="false">
						<div class="avatardiv avatardiv-shown">
															<img alt="" src="/cloud/index.php/avatar/jason/32?v=0" srcset="/cloud/index.php/avatar/jason/64?v=0 2x, /cloud/index.php/avatar/jason/128?v=0 4x" width="32" height="32">
													</div>
						<div id="expandDisplayName" class="icon-settings-white"></div>
					</div>
					<nav class="settings-menu menu" id="expanddiv" style="display:none;" aria-label="Settings menu">
					<ul>
											<li data-id="settings">
							<a href="/cloud/index.php/settings/user">
								<img alt="" src="/cloud/settings/img/admin.svg?v=d1f5d314">
								Settings							</a>
						</li>
											<li data-id="core_apps">
							<a href="/cloud/index.php/settings/apps">
								<img alt="" src="/cloud/settings/img/apps.svg?v=d1f5d314">
								Apps							</a>
						</li>
											<li data-id="core_users">
							<a href="/cloud/index.php/settings/users">
								<img alt="" src="/cloud/settings/img/users.svg?v=d1f5d314">
								Users							</a>
						</li>
											<li data-id="firstrunwizard-about">
							<a href="">
								<img alt="" src="/cloud/apps/firstrunwizard/img/info.svg?v=d1f5d314">
								About							</a>
						</li>
											<li data-id="help">
							<a href="/cloud/index.php/settings/help">
								<img alt="" src="/cloud/settings/img/help.svg?v=d1f5d314">
								Help							</a>
						</li>
											<li data-id="logout">
							<a href="/cloud/index.php/logout?requesttoken=BADB47W19B9KK7Q8468nSdMK96%2BevlM4VQ4ubcM0a%2BI%3D%3Afli7jZqMh34%2BBIR22tpKeLpJnMn78RlUbXdFJvVaGIg%3D">
								<img alt="" src="/cloud/core/img/actions/logout.svg?v=d1f5d314">
								Log out							</a>
						</li>
										</ul>
					</nav>
				</div>
			</div>
		</header>

		<div id="sudo-login-background" class="hidden"></div>
		<form id="sudo-login-form" class="hidden">
			<label>
				This action requires you to confirm your password<br>
				<input type="password" class="question" autocomplete="new-password" name="question" value=" " placeholder="Confirm your password">
			</label>
			<input class="confirm" value="Confirm" type="submit">
		</form>

		<div id="content" class="app-passwords" role="main">
			    <span data-constant="imagePath" data-value="/cloud/apps/passwords/img/"></span>
    <div id="app" class="passwords"><div id="app-navigation"><ul class="menu-main"><li><a href="#/all" class=""><span><i aria-hidden="true" class="fa fa-globe"></i>
    All
    </span></a></li> <li><a href="#/folders" class="router-link-exact-active active"><span><i aria-hidden="true" class="fa fa-folder"></i>
    Folders
    </span></a></li> <li><a href="#/recent" class=""><span><i aria-hidden="true" class="fa fa-clock-o"></i>
    Recent
    </span></a></li> <li><a href="#/favorites" class=""><span><i aria-hidden="true" class="fa fa-star"></i>
    Favorites
    </span></a></li> <li><a href="#/shared" class=""><span><i aria-hidden="true" class="fa fa-share-alt"></i>
    Shares
    </span></a></li> <li><a href="#/tags" class=""><span><i aria-hidden="true" class="fa fa-tag"></i>
    Tags
    </span></a></li> <li><a href="#/security" class=""><span><i aria-hidden="true" class="fa fa-shield"></i>
    Security
    </span></a></li> <!----></ul> <ul class="menu-secondary"><!----> <li><a href="#/trash" class=""><span><i aria-hidden="true" class="fa fa-trash"></i>
    Trash
    </span></a></li></ul> <ul id="app-settings" class=""><li class="more"><a class=""><i aria-hidden="true" class="fa fa-plus"></i>
    More
    </a></li> <li><a href="#/settings" class=""><span><i aria-hidden="true" class="fa fa-cog"></i>
    Settings
    </span></a></li> <li><a href="#/backup" class=""><span><i aria-hidden="true" class="fa fa-archive"></i>
    Backup and Restore
    </span></a></li> <li><a href="#/help" class=""><span><i aria-hidden="true" class="fa fa-question-circle"></i>
    Handbook
    </span></a></li> <li><a href="#/apps" class=""><span><i aria-hidden="true" class="fa fa-puzzle-piece"></i>
    Apps &amp; Extensions
    </span></a></li></ul></div> <div id="app-content" class="show-details section-folders"><div class="app-content-left"><div id="controls"><div id="app-navigation-toggle" class="icon-menu"></div> <div class="breadcrumb"><div data-dir="/" class="crumb svg"><a href="#/folders" class="home router-link-exact-active router-link-active">&nbsp;</a></div> <div class="crumb svg first current"><a href="#/folders" class="router-link-exact-active router-link-active" data-folder-id="00000000-0000-0000-0000-000000000000" data-drop-type="folder">Folders
            </a></div> <!----> <div class="passwords-more-menu actions"><span class="button new"><span class="icon icon-add"></span></span> <div class="popovermenu menu menu-center"><ul><li><span class="menuitem"><span class="icon icon-folder svg"></span> <span class="displayname"><!---->
    New Folder
    </span></span></li> <li><!----></li> <li><span class="menuitem"><span class="icon icon-filetype-text svg"></span> <span class="displayname"><!---->
    New Password
    </span></span></li> <li><!----></li> <li><!----></li></ul></div></div> </div></div> <div class="item-list"><div class="row header"><span title="Sort by name" class="title asc"><!---->
    Name
    </span> <span title="Sort by modified date" class="date"><!---->
    Modified
    </span></div>   <div data-password-id="deac505b-5a0e-45c4-ba97-71ceceae372d" data-password-title="test-name" class="row password" draggable="true"><i class="fa fa-star favorite active"></i> <img src="https://sample-domain.com/cloud/index.php/apps/passwords/api/1.0/service/favicon/www.google.com/32" title="test-name" loading="lazy" alt="" class="favicon"> <div title="test-name" class="title"><span>test-name</span></div> <!---->  <i title="Secure" class="fa fa-shield security ok"></i> <div class="more"><i class="fa fa-ellipsis-h"></i> <div class="passwordActionsMenu popovermenu bubble menu"><ul> <li><i aria-hidden="true" class="fa fa-info"></i>
    Details
    </li> <li><i aria-hidden="true" class="fa fa-share-alt"></i>
    Share
    </li> <li><i aria-hidden="true" class="fa fa-pencil"></i>
    Edit
    </li> <!----> <!----> <li><i aria-hidden="true" class="fa fa-clipboard"></i>
    Copy Url
    </li> <li><a href="https://www.google.com" target="_blank"><i aria-hidden="true" class="fa fa-link"></i>
    Open Url
    </a></li> <li><i aria-hidden="true" class="fa fa-trash"></i>
    Delete
    </li> </ul></div></div> <div title="Last modified on January 5, 2020 1:11 AM" class="date">10 hours ago</div></div> <div class="row footer"><div title="1 password" class="title"><span><!---->
    1 password
    </span> <!----> <!----></div></div> <!----></div></div> <div class="app-content-right"><div class="item-details"><i class="fa fa-times"></i> <div class="preview-container"><a href="https://www.google.com/" target="_blank" rel="noreferrer noopener" title="Go to https://www.google.com/" class="inner-container link">
    
    <div class="loader"><img src="https://sample-domain/cloud/index.php/apps/passwords/api/1.0/service/favicon/google.com/96" alt=""></div> <div class="image s1" style="margin-top: 0px;"><img src="https://sample-domain/cloud/index.php/apps/passwords/api/1.0/service/preview/www.google.com/desktop/640/360..." alt=""></div></a></div> <div title="test-name" class="title"><img src="https://sample-domain/cloud/index.php/apps/passwords/api/1.0/service/favicon/www.google.com/32" alt="" class="icon"> <h3>test-name</h3></div> <div class="infos"><i class="fa fa-star favorite active"></i> <span class="date">1/5/2020</span> <div class="tags-container"><ul class="tags"></ul> <input type="text" placeholder="Add Tags..." class="add-tags"> <!----></div></div> <div class="tab-container"><ul class="tab-titles"><li data-tab="details" class="tab-title"><!---->
    Details
    </li><li data-tab="notes" class="tab-title"><!---->
    Notes
    </li><li data-tab="share" class="tab-title active"><!---->
    Share
    </li><li data-tab="revisions" class="tab-title"><!---->
    Revisions
    </li></ul> <div class="tab-contents"><div class="tab-content active"><div><div class="tab-container"><ul class="tab-titles"><li data-tab="nextcloud" class="tab-title active"><!---->
    Share
    </li><li data-tab="qrcode" class="tab-title"><!---->
    QR Code
    </li></ul> <div class="tab-contents"><div class="tab-content active"><div class="sharing-container password-share-nextcloud"><!----> <!----> <input data-v-6620c483="" type="text" value="" placeholder="Search user" class="share-add-user"> <ul class="shares"><li title="Some data is waiting to be synchronized" class="share" data-share-id="13b8243a-a99b-4436-ae03-9767ceae19a0"><div class="options"><span title="Toggle write permissions" class=""><i aria-hidden="true" class="fa fa-pencil"></i>
    
    <!----></span> <span title="Toggle share permissions" class="active"><i aria-hidden="true" class="fa fa-share-alt"></i>
    
    <!----></span> <span title="Set expiration date" class=""><i aria-hidden="true" class="fa fa-calendar"></i>
    
    <!----></span> <span title="Stop sharing"><i aria-hidden="true" class="fa fa-trash"></i>
    
    <!----></span></div> <img src="https://sample-domain/cloud/index.php/apps/passwords/api/1.0/service/avatar/user/32" alt="user" loading="lazy" class="avatar"> <div class="loading"></div>
    user
</li></ul> <!----></div></div></div></div></div></div></div></div></div></div></div> <div id="app-popup"><div></div></div> <!----> <!----> <!----></div>
		</div>

	

<div id="rightClickMenus"></div><div id="rightClickDetector"></div>




```

</details>

**Comment by a-net** [comment]
![nextcloud-password-spinning-icon](https://user-images.githubusercontent.com/8510667/71785225-ebccb600-2fb1-11ea-86b2-8ba125d7a446.jpg)

**Comment by a-net** [comment]
screenshot of spinning icon:
![nextcloud-password-spinning-user-icon](https://user-images.githubusercontent.com/8510667/71785614-73b4bf00-2fb6-11ea-9fc2-9844526de944.jpg)

**Comment by marius-wieschollek** [comment]
I assume that there is an issue in the background synchronization job.
Please enable logging. Then run `./occ config:app:delete passwords cron/sharing/time` and open the details view for sharing again. It should attempt to execute the background job and log any issues with that.

**Comment by L1ghtF1r3** [comment]
I have the same issue and tried `./occ config:app:delete passwords cron/sharing/time` . It still doesnt work

Nextcloud is installed and hosted by allinkl on a Subdomain. Cronjobs are executed every five minutes. 
PHP Version: 7.3

**Comment by marius-wieschollek** [comment]
Can you please enable Nextcloud logging.

After that run `./occ config:app:delete passwords cron/sharing/time`

Then open the frontend again and after that check if any errors were logged in the Nextcloud log.

**Comment by L1ghtF1r3** [comment]
With Nextcloud logging you mean what you can find in the Nextcloud-Frontend: Settings -> Logging?

It was already enabled and it just shows: `Info | occweb | config:app:delete passwords cron/sharing/time` when I run it

**Comment by marius-wieschollek** [comment]
so there are no errors at all?

**Comment by L1ghtF1r3** [comment]
Not after running this command.
However sometimes there is `Warning | passwords | Cancelled expired session **** for User`

EDIT: not sure, whether it is important or not, but I disabled Legacy Api Support

**Comment by marius-wieschollek** [comment]
That is strange. As soon as you try to share something or just look at the shared tab of a password with the spinning wheel it should try to run the sharing cron job. 

The `config:app:delete passwords cron/sharing/time` should remove the lock file which prevents the job from running if it is already running (or crashed).

Running that job should at least cause some log messages.

**Comment by marius-wieschollek** [comment]
Ideally it should work like this:

![ezgif com-optimize](https://user-images.githubusercontent.com/8255857/72350883-92663480-36df-11ea-8c56-5af9496db1d1.gif)

**Comment by L1ghtF1r3** [comment]
It looks exactly like this, except there is no Error in the logs.

**Comment by L1ghtF1r3** [comment]
Is there a way to print Logfile-Entries when the Backgroundjob is executed?

**Comment by L1ghtF1r3** [comment]
I just tried to rename `SynchronizeShares.php` located at `/apps/passwords/lib/Cron` to see, if it gives me an error at all - but it doesnt. It looks like it is not executing that Backgroundjob at all.

Not sure if it's a problem but nextcloud is located on a Subdomain in a Subfolder, working ith redirects / rewrites in .htaccess ( like `https://www.subdomain.domain.de/nextcloud` )

**Comment by marius-wieschollek** [comment]
If you renamed the file there should definitely be an error, even when the job is not executed. Nextcloud would try to load the file and fail. Maybe Opcache is configured to not validate?

The background job also usually creates debug or info message if it runs.

What you could do to see if it tries to execute the job is to press F12 in the browser, open the network tab and filter for requests with `cron/sharing`. As soon as you open the sharing tab, there should be a request to `https://www.subdomain.domain.de/nextcloud/index.php/apps/passwords/cron/sharing` every five seconds. The response is either `{"success":true}` if everything went ok, or `{"success":false}` if the job failed or was not executed because it is still locked by a previous job.

You could also check the error log of your server. PHP errors may get logged there.

**Comment by L1ghtF1r3** [comment]
It responsed with `{"success":false}`

**Comment by L1ghtF1r3** [comment]
I use the business-membership from all-inkl.com/
I cant change PHP settings or read logfiles there

**Comment by marius-wieschollek** [comment]
What you could do is to edit `execute` in `lib/Controller/CronController.php` and replace 

```
            if($job === 'sharing') {
                return new JSONResponse(['success' => $this->synchronizeShares->runManually()]);
            }
```
with
```
        try {
            if($job === 'sharing') {
                return new JSONResponse(['success' => $this->synchronizeShares->runManually()]);
            }
        } catch(\Throwable $e) {
            return new JSONResponse(['success' => false, 'exception' => $e], Http::STATUS_NOT_FOUND);
        }
```

You also need to edit `runManually` in `Cron/SynchronizeShares.php` and replace

```
        } catch(\Exception $e) {
            $this->logger->logException($e);
        }
```
with
```
        } catch(\Exception $e) {
            $this->logger->logException($e);
            throw $e;
        }
```

With that run `config:app:delete passwords cron/sharing/time` again and the http request should now also return an exception.

**Comment by L1ghtF1r3** [comment]
Guten Morgen ;)

I tried this but it returns no exeption or error at all. It seems like the backgroundjob does not run at all.

**Comment by L1ghtF1r3** [comment]
It seems like this:
`    protected function canExecute(): bool {
        return $this->environment->getRunType() === EnvironmentService::TYPE_CRON &&
               $this->config->getAppValue(self::EXECUTION_TIMESTAMP, 0) < strtotime('-4 hours');
    }`
in `/lib/Cron/SynchronizeShares.php` always returns false. But I cant figure out why..


When I replace `===` with `!==` it returns true, but my php skills are to low to understand what this function does..

**Comment by marius-wieschollek** [comment]
Thanks for that info.
I think that the app can't detect that it is running as cron job.

**Comment by L1ghtF1r3** [comment]
strange issue / error when I change `===` in `!==` in `/lib/Cron/SynchronizeShares.php` and try to share a password with an other User.

I

replaced: 
- `[Nextcloud-URL]` from `/www/htdocs/......`
- `[USERID]` from the actual Username (no illegal Charakters or too long Username

`[passwords] Error: Exception: User key requested with illegal user id: USERID at <<closure>>

 0. [Nextcloud-URL]/apps/passwords/lib/Encryption/Object/SseV1Encryption.php line 195
    OCA\Passwords\Encryption\Object\SseV1Encryption->getUserKey("USERID")
 1. [Nextcloud-URL]/apps/passwords/lib/Encryption/Object/SseV1Encryption.php line 121
    OCA\Passwords\Encryption\Object\SseV1Encryption->getEncryptionKey("cuqwnw5XzC1qio6 ... P", "[USERID]")
 2. [Nextcloud-URL]/apps/passwords/lib/Services/EncryptionService.php line 95
    OCA\Passwords\Encryption\Object\SseV1Encryption->encryptObject("*** sensitive parameters replaced ***")
 3. [Nextcloud-URL]/apps/passwords/lib/Services/Object/AbstractRevisionService.php line 147
    OCA\Passwords\Services\EncryptionService->encrypt("*** sensitive parameters replaced ***")
 4. [Nextcloud-URL]/apps/passwords/lib/Cron/SynchronizeShares.php line 225
    OCA\Passwords\Services\Object\AbstractRevisionService->save("*** sensitive parameter replaced ***")
 5. [Nextcloud-URL]/apps/passwords/lib/Cron/SynchronizeShares.php line 114
    OCA\Passwords\Cron\SynchronizeShares->createNewShares()
 6. [Nextcloud-URL]/apps/passwords/lib/Cron/SynchronizeShares.php line 129
    OCA\Passwords\Cron\SynchronizeShares->runJob(null)
 7. [Nextcloud-URL]/apps/passwords/lib/Controller/CronController.php line 55
    OCA\Passwords\Cron\SynchronizeShares->runManually()
 8. [Nextcloud-URL]/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Passwords\Controller\CronController->execute("sharing")
 9. [Nextcloud-URL]/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Passwords\Co ... {}, "execute")
10. [Nextcloud-URL]/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "execute")
11. [Nextcloud-URL]/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Passwords\ ... r", "execute", OC\AppFramework\ ... {}, {job: "sharing", ... "})
12. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({job: "sharing", ... "})
13. [Nextcloud-URL]/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {job: "sharing", ... "})
14. [Nextcloud-URL]/lib/base.php line 997
    OC\Route\Router->match("/apps/passwords/cron/sharing")
15. [Nextcloud-URL]/index.php line 42
    OC::handleRequest()

GET /nextcloud/index.php/apps/passwords/cron/sharing
from IP by USER at 2020-01-15T12:50:27+00:00`

**Comment by marius-wieschollek** [comment]
I am able to reproduce the issue now and will push a patch to the nightlies soon. The issue is not in the sharing job itself and just changing the comparison won't fix it. The error you get is the result of your account trying to access a password of another account.

Since this is an http request, a username is present and the app limits all actions to the privileges of this user. Only if the app recognizes that it is running a cron job, it will process the shares correctly. This detection does not work.

**Comment by L1ghtF1r3** [comment]
looking forward to this, thanks for your patience and support!

**Comment by marius-wieschollek** [comment]
I have published [2020.2.0-build3342](https://apps.nextcloud.com/apps/passwords) which should fix this error.

You can install the nightly by downloading it from the app store and uploading it to your server. You can also try and check the `Show Nightly Updates in "Apps"` option in the settings, but i assume that it will not work because of this issue.

**Comment by L1ghtF1r3** [comment]
Im sorry to tell you, that its not working.
In the logs it sais:

`[PHP] Error: Undefined property: stdClass::$isTokenLogin at [URL]/apps/passwords/lib/Services/EnvironmentService.php#435

GET /nextclouod/index.php/settings/admin/logging
from [IP]by USER at 2020-01-16T07:35:25+00:00`

**Comment by marius-wieschollek** [comment]
That problem should now be fixed too

**Comment by L1ghtF1r3** [comment]
The error disappeared but sharing a password is still not working

**Comment by bushrang3r** [comment]
I have this problem with **version 18.0.3.**
After sharing a password (to only one user) the spinning animation never ends and the password is not shared and the same message "Some data is waiting to be synchronized" appears. Refreshing the page also turns the password shield red (breached). I don't know if that's related.

[passwords] Error: OCA\Passwords\Cron\SynchronizeShares must be executed as cron job
GET /nextcloud12345/cron.php
from 183.77.216.153 at 2020-04-03T02:22:55+00:00

OCA\Passwords\Cron\ProcessDeletedEntities must be executed as cron job
OCA\Passwords\Cron\CheckPasswordsJob must be executed as cron job
OCA\Passwords\Cron\SynchronizeShares must be executed as cron job
OCA\Passwords\Cron\SendServerSurvey must be executed as cron job

**Comment by marius-wieschollek** [comment]
I have checked this again and hope it works now. You can check the 2020.4.1 nightly version if it works for you.

**Comment by marius-wieschollek** [comment]
I have released 2020.4.1. I will consider this issue fixed if no one says otherwise.
