### ISSUE TITLE
Migration following migration proposal fails

### ISSUE THREAD

**Issue by chrsch** [marius-wieschollek/passwords#49]
### System Information
- Nextcloud Version: 12.0.7
- PHP Version: 7.1
- Passwords Version 2018.5.2
- Browser and Version: FF 60
- Client OS and Version: na
- Server OS and Version: Ubuntu LTS 14.04

### Steps to reproduce
1. Tell us how to reproduce your issue.
- This is an update from ownCloud to Nextcloud (oC 9.1.8 to nc 10 -> nc 11 -> nc 12.0.7).
- Passwords legacy app in oC 9.1.8 is version 20-beta9
- nc10 and 11 have no password app installed in the migration path
- After going through this in nc 12.0.7 install passwords 2018.5.2
- Trigger update by "occ config:app:set passwords installed_version --value 2017.12" and afterwards "occ upgrade" like described here: https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration 

### Actual result
In the upgrade process errors are thrown, e. g. 
 0/3 [>---------------------------]   0%Repair warning: Failed migrating password #4: Too few arguments to function OCA\Passwords\Services\Object\PasswordRevisionService::create(), 13 passed in /var/nextcloud/apps/passwords/lib/Migration/Legacy/LegacyPasswordMigration.php on line 141 and exactly 14 expected in /var/nextcloud/apps/p... [message is cut here]

### Expected result
Migration should run without errors and passwords should show up.

Furthermore, if I try to run again by repeating "occ config:app:set passwords installed_version --value 2017.12" and afterwards "occ upgrade" the upgrade mechanism is no longer triggered. Is this intended?

**Comment by marius-wieschollek** [comment]
I will look at it and tell you when a nightly release with a fix is available.

**Comment by chrsch** [comment]
If you need any further information don't hesitate and let me know :-)

**Comment by marius-wieschollek** [comment]
The nightly build [2018.6.0-build2263](https://apps.nextcloud.com/apps/passwords/releases?platform=12#12) should fix this.

**Comment by chrsch** [comment]
Great news, I'll give it a try tomorrow and let you  know if it worked.

**Comment by chrsch** [comment]
Gave it a try but I still get the same error message. Double checked I used the nightly and did so.

**Comment by marius-wieschollek** [comment]
Ok. The cause of the exception was that the line `lib/Migration/Legacy/LegacyPasswordMigration.php:138` should be `'{}',` followed by `FolderService::BASE_FOLDER_UUID,`. Can you check if that is the case for you?

I ran the whole migration from a 20-beta9 database of the old app this morning and the migration worked. However i noticed that the customFields migration will leave you in an endless upgrade loop in this nightly build. I fixed that now. Before you retry the migration, make sure that the new tables `passwords_entity_folder, passwords_entity_folder_revision, passwords_entity_password, passwords_entity_password_revision, passwords_entity_share, passwords_entity_tag, passwords_entity_tag_revision, passwords_relation_password_tag` are empty and do not contain any data from a failed attempt. (But dont'd delete them, just truncate them. And also make sure not to damage the old tables - make a backup if needed)

**Comment by chrsch** [comment]
In the nightly linked above lines 137-139 are these:
137:            $this->getNotes($properties, $password, $key),
138:            FolderService::BASE_FOLDER_UUID,
139:            $timestamp, false,`

So I assume the fix is actually not in there? The tables mentioned above are empty.

**Comment by chrsch** [comment]
But this is not the only issue. Manually added the missing line but at least with the nightly I get another error: lib/private/Repair.php on line 105 and exactly 4 expected in /var/www/nextcloud/apps/passwords/lib/Migration/LegacyDatabaseMigration.php:55

**Comment by marius-wieschollek** [comment]
can you download this [build](https://git.mdns.eu/nextcloud/passwords/-/jobs/6323/artifacts/raw/passwords.tar.gz) and install it? Afterwards go to the addons page and check if the version is reported as 2018.6.0-build2271. It should contain the current code and work properly.

**Comment by chrsch** [comment]
Check, this build works, passwords do migrate. Thanks for providing this additional build :-)

**Comment by marius-wieschollek** [comment]
:fireworks: Yay. Thats great to hear.
