### ISSUE TITLE
[BUG]: Wrong (default) background image in E2E encryption Password dialog

### ISSUE THREAD

**Issue by fuse314** [marius-wieschollek/passwords#588]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "25.0.6.1",
        "app": "2023.4.30",
        "lsr": false,
        "php": "8.1.18",
        "cronPhp": "8.1.18"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "webcron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "ddg",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": true,
            "default": "none"
        },
        "cse": {
            "CSEv1r1": true,
            "none": true,
            "default": "CSEv1r1"
        }
    }
}
```

### Client Information

Browser and Version: Brave [Version 1.50.121 Chromium: 112.0.5615.138 (Offizieller Build) (64-Bit)]
Client OS and Version: Windows 11 22H2

### Bug description

Wrong background image is displayed in E2E encryption Password dialog.

This is in the application

### Steps to reproduce

1. Enable Theming app, set custom (svg) background image and background color.
2. Set E2E encryption password in Passwords app.
3. Open Passwords app, the "Enter Password" dialog is displayed with the default Nextcloud background image.

This is the same in the browser extension. (background color is set correctly, background image is wrong).

![passwords_theming_NC25](https://user-images.githubusercontent.com/927896/234887523-6e63638b-b005-4cd3-8ffb-df8960ec2985.gif)

### Expected behavior

3. Open Passwords app, the "Enter Password" dialog is displayed with the custom color and the custom background image.

### Nextcloud Logs

```shell
The Nextcloud log is empty.
```

### Browser Logs

```shell
Various requests...
After .css/.js files:
Request to get
https://[server]/core/img/app-background.jpg => default background image.

...after a few more requests:
Request to https://[server]/apps/theming/manifest/passwords?vXXXXXXXX
Response:
{
  ...
background_color: "#007D03" (correct)
theme_color: "#007D03" (correct)
}
```

**Comment by fuse314** [comment]
probably related to #586 (Nextcloud 26), but this issue concerns Nextcloud 25.

**Comment by marius-wieschollek** [comment]
This should be working with the latest update

**Comment by fuse314** [comment]
Hi @marius-wieschollek
I finally got around to installing the nightly version of passwords ``2023.7.30-build4960`` on my Nextcloud ``25.0.7`` instance.
I still see the wrong default (blue background with white clouds) image when prompted for the E2E password and also in the browser extension ``2.2.6.4550``.
Can you take another look into this? - Do you need more information from my installation? Would it help if I upgraded to Nextcloud 26?
Thank you.

**Comment by schmittst** [comment]
Just to confirm: the issue is still there with the latest nextcloud version (27.0.0) and passwords 2023.7.30.
Has also been there before with all nextcloud versions I used.

**Comment by marius-wieschollek** [comment]
The 2023.8 update has fixes for this issue. It works for me on [https://nc25.passwordsapp.org/](https://nc25.passwordsapp.org/info.html).

Can you confirm it works for you?

**Comment by fuse314** [comment]
Thank you, with the 2023.8 update the background is correctly displayed in the browser extension and in the web interface 👍
