### ISSUE TITLE
[BUG]: Login fails with internal server error - Nextcloud 30.0.2 - Passwords 2024.9.20

### ISSUE THREAD

**Issue by bgbearcatfan** [marius-wieschollek/passwords#686]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
It looks like Passwords 2024.9.20 causes internal server error with Nextcloud 30.0.2.

Running the command, sudo -u wwwrun php /srv/www/htdocs/nextcloud/occ app:disable passwords, allows access to nextcloud again.
```

### Client Information

Firefox 131.0.3
Linux Mint 22

### Bug description

Enabling Passwords app 2024.9.20, causes 500 internal error with Nextcloud 30.0.2

### Steps to reproduce

Enable Passwords app
Open Nextcloud URL
Receive 500 internal server error

### Expected behavior

Enable Passwords app
Open Nextcloud URL
Successfully login

### Nextcloud Logs

```shell
Info   passwords   Passwords runs /srv/www/htdocs/nextcloud/occ in global mode                                                                                                                          2024-11-07T18:38:25+00:00 

Info   user_ldap   OCA\User_LDAP\LoginListener - 6B7132DB-B1CF-419A-BC55-85B063320366 postLogin                                                                                                         2024-11-07T18:38:26+00:00 

Warning   passwords   Login attempt with invalid session for 0817C1A3-5A2D-4E92-8450-FBAB53CBEB1C                                                                                                          2024-11-07T18:38:27+00:00 

Warning   user_ldap   Bind failed: 49: Invalid credentials                                                                                                                                                 2024-11-07T18:38:27+00:00 

Warning   user_ldap   Bind failed: 49: Invalid credentials                                                                                                                                                 2024-11-07T18:38:27+00:00 

Info   user_ldap   OCA\User_LDAP\LoginListener - 6B7132DB-B1CF-419A-BC55-85B063320366 postLogin                                                                                                         2024-11-07T18:38:27+00:00 

Warning   passwords   Login attempt with invalid session for 0817C1A3-5A2D-4E92-8450-FBAB53CBEB1C                                                                                                          2024-11-07T18:38:28+00:00 

Warning   user_ldap   Bind failed: 49: Invalid credentials                                                                                                                                                 2024-11-07T18:38:28+00:00 

Warning   user_ldap   Bind failed: 49: Invalid credentials                                                                                                                                                 2024-11-07T18:38:28+00:00 

Info   user_ldap   OCA\User_LDAP\LoginListener - 0817C1A3-5A2D-4E92-8450-FBAB53CBEB1C postLogin
```

**Comment by PeopleInside** [comment]
I have the same issue.
What is the solution for now? Restore the nextcloud backup from my server and wait until a fix is not available before run any update?

https://help.nextcloud.com/t/internal-server-error-after-updating-to-30-0-2-inaccessible/209347/2

After hard work I restored nextcloud and now cannot update, I need wait a fix for passwords app.
I cannot stay with the password app disabled :) so need to restore all from a backup.
This create some issue I lost some data of yesterday but now passwords works back again but the issue still be present and need to be fixed because I cannot upgrade nextcloud to avoid the fatal error.

**Comment by MaxRower** [comment]
Same problem here, on two servers, had to deactivate the app.

**Comment by PeopleInside** [comment]
The possible cause:
https://github.com/nextcloud/server/pull/48939

A comment of a possibile fix:
https://github.com/marius-wieschollek/passwords/issues/683#issuecomment-2463290594

**Comment by MaxRower** [comment]
> The possible cause: [nextcloud/server#48939](https://github.com/nextcloud/server/pull/48939)
> 
> A comment of a possibile fix: [#683 (comment)](https://github.com/marius-wieschollek/passwords/issues/683#issuecomment-2463290594)

The fix works for me, thanks!

**Comment by andyincountry** [comment]
I renamed the "passwords" folder to "passwords.old" in appdata/www/nextcloud/apps and that seems to have let me get back into nextcloud but disables the passwords app.  That is much better than not being able to use nextcloud in general, at least until the passwords app is fixed.

**Comment by MaxRower** [comment]
> I renamed the "passwords" folder to "passwords.old" in appdata/www/nextcloud/apps and that seems to have let me get back into nextcloud but disables the passwords app. That is much better than not being able to use nextcloud in general, at least until the passwords app is fixed.

It's easier to do that on the console, like shown in the first post. Get the fix from above, and everything runs fine again.

**Comment by MacWarrior** [comment]
Hello,

Same issue here, on 2 differents Nextcloud instances, here is trace provided by debug mode.
PHP 8.3.13, with google SSO enabled : 

```
Type : Exception
Code : 0
Message : Unable to verify user google-[...]
Fichier : [...]/apps/passwords/lib/Services/EnvironmentService.php
Ligne : 398

Trace
#0 [...]/apps/passwords/lib/Services/EnvironmentService.php(361): OCA\Passwords\Services\EnvironmentService->loadUserInformation()
#1 [...]/apps/passwords/lib/Services/EnvironmentService.php(185): OCA\Passwords\Services\EnvironmentService->determineAppMode()
#2 [internal function]: OCA\Passwords\Services\EnvironmentService->__construct()
#3 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(61): ReflectionClass->newInstanceArgs()
#4 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#5 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#6 [...]/lib/private/AppFramework/DependencyInjection/DIContainer.php(448): OC\AppFramework\Utility\SimpleContainer->query()
#7 [...]/lib/private/AppFramework/DependencyInjection/DIContainer.php(420): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#8 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\AppFramework\DependencyInjection\DIContainer->query()
#9 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#10 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map()
#11 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#12 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#13 [...]/lib/private/AppFramework/DependencyInjection/DIContainer.php(448): OC\AppFramework\Utility\SimpleContainer->query()
#14 [...]/lib/private/AppFramework/DependencyInjection/DIContainer.php(420): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#15 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\AppFramework\DependencyInjection\DIContainer->query()
#16 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map()
#18 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#19 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#20 [...]/lib/private/AppFramework/DependencyInjection/DIContainer.php(448): OC\AppFramework\Utility\SimpleContainer->query()
#21 [...]/lib/private/ServerContainer.php(137): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#22 [...]/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#23 [...]/lib/private/Settings/Manager.php(175): OC\AppFramework\Utility\SimpleContainer->get()
#24 [...]/lib/private/Settings/Manager.php(323): OC\Settings\Manager->getSettings()
#25 [...]/apps/settings/lib/Controller/CommonSettingsTrait.php(70): OC\Settings\Manager->getAllowedAdminSettings()
#26 [...]/apps/settings/lib/Controller/CommonSettingsTrait.php(105): OCA\Settings\Controller\AdminSettingsController->formatSections()
#27 [...]/apps/settings/lib/Controller/CommonSettingsTrait.php(55): OCA\Settings\Controller\AdminSettingsController->formatAdminSections()
#28 [...]/apps/settings/lib/Controller/CommonSettingsTrait.php(141): OCA\Settings\Controller\AdminSettingsController->getNavigationParameters()
#29 [...]/apps/settings/lib/Controller/AdminSettingsController.php(58): OCA\Settings\Controller\AdminSettingsController->getIndexResponse()
#30 [...]/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\Settings\Controller\AdminSettingsController->index()
#31 [...]/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController()
#32 [...]/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch()
#33 [...]/lib/private/Route/Router.php(302): OC\AppFramework\App::main()
#34 [...]/lib/base.php(1001): OC\Route\Router->match()
#35 [...]/index.php(24): OC::handleRequest()
#36 {main}
```

**Comment by tron65** [comment]
> > The possible cause: [nextcloud/server#48939](https://github.com/nextcloud/server/pull/48939)
> > A comment of a possibile fix: [#683 (comment)](https://github.com/marius-wieschollek/passwords/issues/683#issuecomment-2463290594)
> 
> The fix works for me, thanks!

Works for me too, thanks alot as well

**Comment by MacWarrior** [comment]
> The possible cause: [nextcloud/server#48939](https://github.com/nextcloud/server/pull/48939)
> 
> A comment of a possibile fix: [#683 (comment)](https://github.com/marius-wieschollek/passwords/issues/683#issuecomment-2463290594)

Temp fix confirmed on native account/login, but issue still present when using Google SSO login

**Comment by iacchi** [comment]
The bug is present also in the latest version of NC 29

**Comment by jstrickland2** [comment]
Failed to add app migration step OCA\Passwords\Migration\CliDatabaseObjectRepair

**Comment by joergmschulz** [comment]
> The possible cause: [nextcloud/server#48939](https://github.com/nextcloud/server/pull/48939)
> 
> A comment of a possibile fix: [#683 (comment)](https://github.com/marius-wieschollek/passwords/issues/683#issuecomment-2463290594)

For my installation which only allows login via OIDC, the above fix doesn't seem to work.

**Comment by PeopleInside** [comment]
@joergmschulz , @MacWarrior 
I'm sorry you are still facing issues by the [login with Google SSO](https://github.com/marius-wieschollek/passwords/issues/686#issuecomment-2464096521) and [via OIDC](https://github.com/marius-wieschollek/passwords/issues/686#issuecomment-2466145884)

Unfortunately I cannot help with that as I have just found a fix from a Nextcloud developer that are using maybe the same passwords extension and fixed it.

I tried to report some user still report some issue [here](https://help.nextcloud.com/t/nextclloud-crashes-in-several-apps-with-internal-server-error-after-update-to-30-0-2/209422/2?u=pippin) and the reply was [here](https://help.nextcloud.com/t/nextclloud-crashes-in-several-apps-with-internal-server-error-after-update-to-30-0-2/209422/4?u=pippin).

So I don't know how to help. I hope you will find a fix or a solution soon.
Maybe you can try to open a new discussion also on the community about this specific issue you are facing.

**Comment by marius-wieschollek** [comment]
https://github.com/marius-wieschollek/passwords/issues/683

**Comment by MacWarrior** [comment]
Hello @marius-wieschollek, 

Issue fixed with Passwords 2024.11.20 _(I've also updated Social login to 5.7.0 if it's somehow related)_, thanks !

Best regards,
MacWarrior.

**Comment by nooblag** [comment]
Hi there, thank you, unfortunately for me, the 2024.11.20 patch didn't fix the issue on NC 29.0.9:

![Screenshot 2024-11-10 at 23-17-42](https://github.com/user-attachments/assets/d2e898a3-b567-4a98-bcd6-d3c6586a29fa)

Here's what's in my log:

```
{
  "reqId": "ybVzHVP9Zz5cvHKyoYw7",
  "level": 3,
  "time": "2024-11-10T23:10:04+11:00",
  "remoteAddr": "***removed sensitive value***",
  "user": "***removed sensitive value***",
  "app": "index",
  "method": "GET",
  "url": "/settings/admin/overview",
  "message": "Unable to verify user ***removed sensitive value***",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0",
  "version": "29.0.9.2",
  "exception": {
    "Exception": "Exception",
    "Message": "Unable to verify user ***removed sensitive value***",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php",
        "line": 361,
        "function": "loadUserInformation",
        "class": "OCA\\Passwords\\Services\\EnvironmentService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php",
        "line": 185,
        "function": "determineAppMode",
        "class": "OCA\\Passwords\\Services\\EnvironmentService",
        "type": "->"
      },
      {
        "function": "__construct",
        "class": "OCA\\Passwords\\Services\\EnvironmentService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 83,
        "function": "newInstanceArgs",
        "class": "ReflectionClass",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 128,
        "function": "buildClass",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 146,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 471,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 443,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 96,
        "function": "query",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "function": "OC\\AppFramework\\Utility\\{closure}",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 83,
        "function": "array_map"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 128,
        "function": "buildClass",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 146,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 471,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 443,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 96,
        "function": "query",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "function": "OC\\AppFramework\\Utility\\{closure}",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 83,
        "function": "array_map"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 128,
        "function": "buildClass",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 146,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 471,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/ServerContainer.php",
        "line": 155,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 64,
        "function": "query",
        "class": "OC\\ServerContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Settings/Manager.php",
        "line": 202,
        "function": "get",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Settings/Manager.php",
        "line": 350,
        "function": "getSettings",
        "class": "OC\\Settings\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 93,
        "function": "getAllowedAdminSettings",
        "class": "OC\\Settings\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 128,
        "function": "formatSections",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 78,
        "function": "formatAdminSections",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 164,
        "function": "getNavigationParameters",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php",
        "line": 77,
        "function": "getIndexResponse",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 232,
        "function": "index",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 138,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 331,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 1058,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 49,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php",
    "Line": 398,
    "message": "Unable to verify user ***removed sensitive value***",
    "exception": {},
    "CustomMessage": "Unable to verify user ***removed sensitive value***"
  }
}
```

PHP 8.2.23
nginx 1.18.0
mariadb  Ver 15.1 Distrib 10.6.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
Ubuntu 22.04.4 LTS

**Comment by burdoto** [comment]
still getting the same error as well, after updating yesterday, on november 10th

**Comment by marius-wieschollek** [comment]
I'm closing this issue as duplicate of #683. If you still experience this issue, please make sure to update to the latest available version and ensure PHP OPCode Caches are cleared.

@nooblag `EnvironmentService` line 361 does no longer contain a call to `loadUserInformation`, therefore i assume that this error was not produced by the latest version of the app.

If any of you still experience the issue while on the latest version, please open a new issue with your setup details and log entries.

**Comment by nooblag** [comment]
Thank you for that, clearing the cache resolved the issue! Thank you!
