### ISSUE TITLE
Support Client Side Encryption / E2E

### ISSUE THREAD

**Issue by marius-wieschollek** [marius-wieschollek/passwords#80]
Passwords currently only supports Server Side Encryption. This offers very little protection, since all data required for decryption is available on the server. Passwords should be encrypted in the browser with a key that is unknown to the server. (Master Password) Additional measures should be taken to increase the protection by Server Side Encryption.

### System Information
- Nextcloud Version: 14.0.1
- PHP Version: 7.1
- Passwords Version: 2018.9.1
- Browser and Version: Firefox 62
- Client OS and Version: Ubuntu 18.04
- Server OS and Version: Ubuntu 18.04

### Steps to reproduce
1. Press F12
2. Monitor the Network Tab
3. Check the requests and responses to the passwords api

### Actual result
All data is transferred in plain text.
Data on the server can be encrypted anytime.

### Expected result
Passwords should be encrypted.
Data on the server should be only encryptable when user is logged in.

**Comment by florealcab** [comment]
As it's removed from the 2018.12 milestone, do you know when E2E will be available for this awesome app? E2E is required for me to use this app in production :)

**Comment by rugk** [comment]
Maybe you can just re-use stuff that Nextcloud does for implementing file e2e crypto. It would be great, if it could just use the same key + concept, because that is great.

**Comment by marius-wieschollek** [comment]
CSE got removed from the milestone because i currently do not have the time required to finish the feature. Currently the actual encryption works, but storing the keys does not. I hope to be able to finish the feature in Q1 2019 when the Nextcloud 15 patches are done and i have more time for Passwords in general.

Also after the implementation of CSE in the app, it will take some time to rewrite the browser extension since it still uses the legacy API which will not support CSE in any way.

**Comment by marius-wieschollek** [comment]
I have been able to make some progress and implement the client side encryption using the libsodium library. The encryption works, the key management works, impersonating is supported (#116), master password and 2FA also work. The api is quite a bit faster with client side encryption (around 50%) as it causes less server load. However there are still some glitches and the strong server side encryption is not implemented. Backups are still missing some important data (like the keys), you can currently not change your master password, any client (Android App, Browser Extension) does not support CSE right now and the encryption preference settings are also missing. Once CSE is enabled, it can not be deactivated. This might be changed in the future, but has a low priority.

If you want, can try out the build linked below but i would strongly recommend doing that on a test system such as the developer environment. This is more a tech-preview than a stable product and some changes made in the future may be incompatible with its current status. You can look at the source code in the [libsodium branch](https://github.com/marius-wieschollek/passwords/tree/libsodium) or download the [build](https://git.mdns.eu/nextcloud/passwords/-/jobs/artifacts/libsodium/download?job=Assemble). To enable CSE, go to the settings and start the "Client Side Encryption" field test.

**Comment by MikeLauer** [comment]
Any updates about CSE? I really like the app but I don't trust SSE-only. I would like to use it though...

**Comment by marius-wieschollek** [comment]
> Any updates about CSE?

Compared to February there has been some progress. There is now a proper CSE setup dialog. You can change your password. The login procedure has been redesigned to be more secure. If someone tries to use the wrong password more than 5 times, you will be notified and the client will be blocked. SSEv2 is now available and gives you the option to use a more secure encryption even without CSE. You can specify which encryption to use by default.

I will keep you updated once code is shipped.

**Comment by marius-wieschollek** [comment]
Code for E2E and SSEv2 will be included in the 2019.7.0 version along a lot of other new features. However it will be disabled in any regular version of the app until the official apps have been upgraded.

Documentation for developers and admins will come in the following weeks.

Most features can be tested in the nightlies which you can install by enabling `Show Nightly Updates in "Apps"` in the admin settings. *Be aware that functionality from nightlies might still be buggy or can be changed until the final version arrives.*

**Comment by szaimen** [comment]
If I understood the feature correctly, if E2E is enabled, you have to enter your 2FA-Key of your nextcloud account when accessing the app? I think a better option would probably be a masterpassword.
Is this already beeing discussed or shall I open a new issue to track this?

**Comment by marius-wieschollek** [comment]
@szaimen No. The 2FA will is a separate feature. If it is enabled the app will require the 2FA-Method when you open it. If the E2E is enabled it will also require the Masterpassword.

**Comment by despens** [comment]
The [README](https://github.com/marius-wieschollek/passwords/blob/master/README.md) currently states:

> Client Side Encryption (E2E)
>
> You can have your passwords encrypted in your browser. This will protect them from unauthorized access and even keep them safe if the server is hacked.

This doesn't seem to be right at the moment, maybe it would be better to remove that info unless E2E is actually available?

**Comment by marius-wieschollek** [comment]
@despens You can actually enable E2E [on your server](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/User-Handbook#self-hosting-the-handbook). I have updated the readme to include that.

**Comment by TheCrowned** [comment]
So do I understand correctly when I say that E2E is still not fully operational? From Marius last comment I guess it is *possible* to torn it on, but also "Enabling features which are disabled by default can cause issues and is not supported".

**Comment by anmolnar** [comment]
@TheCrowned I tested E2E recently and it works as expected and can be enabled by the method that @marius-wieschollek suggested. But this is from App side only, the feature is still not supported by any of the known clients (Firefox, Chrome plugin, mobile app is completely useless) and until that enabling it doesn't make sense to me.

**Comment by TheCrowned** [comment]
> the feature is still not supported by any of the known clients

Yes, that was the point :)

**Comment by marius-wieschollek** [comment]
I have updated https://github.com/marius-wieschollek/passwords-webextension/issues/72 with some information on the new browser extension.

A development build with automatic updates can be downloaded as [signed XPI file for Firefox](https://git.mdns.eu/nextcloud/passwords-webextension/-/jobs/artifacts/testing/browse/dist/firefox-extension?job=Publish+Nightly+Firefox). This extension is a work in progress and will contain bugs and incomplete features.

If you want to test CSE/E2E, you should at least use version 2020.2.0 of the app. I have changed the encoding of the encrypted strings to reduce the file size. Users who already use CSE don't need to worry as the old encoding is still supported and will be detected automatically.

**Comment by janpekar** [comment]
I would prefer easier way how to enable CSE/E2E encryption, than via publishing handbook somewhere. It is another public hosted project. How about to change it via occ config way? 
Please let me know if there will be any new app release with easier CSE config  and when it will be deployed.
Thank you

**Comment by marius-wieschollek** [comment]
@janpekar you can just install the nightly where it's enabled all the time.

**Comment by marius-wieschollek** [comment]
I'm happy to report that e2e/cse is available in all versions since 2020.12.1.
It's also supported by the official browser extension in version 2.0.0 and later.

And for those who would like an app with that: [the Android app by joleaf also supports e2e now.](https://gitlab.com/joleaf/nc-passwords-app)
You can get it from F-Droid: https://f-droid.org/de/packages/de.jbservices.nc_passwords_app/
or Google Play: https://play.google.com/store/apps/details?id=de.jbservices.nc_passwords_app

**Comment by piti-diablotin** [comment]
Hi

First allow me to thank you for you great work ! 
I just enable CSE and now when I open the details of one password, it says 
`Encryption on server No encryption` while `Encryption on client Encryption with libsodium`.

I understand that **it is** encrypted on the server but maybe the `Encryption with libsodium` should be displayed also for the server ? Or something saying that is securely stored on the serve ?

Thanks again

**Comment by marius-wieschollek** [comment]
Well, since that section is supposed to show which encryption is applied where, maybe a more fitting label could be "Encryption applied by the server" and "Encryption applied by the client"?

**Comment by piti-diablotin** [comment]
Something like that yes :smile:

**Comment by despens** [comment]
Is there a way to share e2e encrypted passwords with different users, like for example Bitwarden does? When I try to share an e2e password with another user, I'm getting a warning that it will be changed to be server-side encrypted. Maybe I'm doing something wrong here?

**Comment by marius-wieschollek** [comment]
No. The warning is correct.

**Comment by squintarelli** [comment]
> I just enable CSE and now when I open the details of one password, it says
> `Encryption on server No encryption` while `Encryption on client Encryption with libsodium`.

Where did you do it ? I'm not able to find such setting...
maybe it's now always enabled ?

**Comment by TtuxX** [comment]
> > I just enable CSE and now when I open the details of one password, it says
> > `Encryption on server No encryption` while `Encryption on client Encryption with libsodium`.
> 
> Where did you do it ? I'm not able to find such setting...
> maybe it's now always enabled ?

This section is visible when you select the `Advanced` view from the `Options` menu at the bottom of the left panel inside the Passwords app.

**Comment by squintarelli** [comment]
> This section is visible when you select the `Advanced` view from the `Options` menu at the bottom of the left panel inside the Passwords app.

Thanks for the quick reply!
I am not able to find it :-(
This is the menu I have in the app at the bottom left: https://i.imgur.com/K3g5tm0.png
Under <code>Settings</code> there's an <code>Advanced</code> view but I can't find any option to enable CSE https://i.imgur.com/vsYyHKW.png

**Comment by marius-wieschollek** [comment]
@squintarelli E2E is available in version 2020.12.2 and later. Then you should see the point "End-to-End Encryption" at the end of the security section.
See: https://git.mdns.eu/nextcloud/passwords/wikis/Users/Settings
And here is the guide to enable the E2E with all additional information: https://git.mdns.eu/nextcloud/passwords/wikis/Users/Encryption/Enable-End-to-End-Encryption

**Comment by squintarelli** [comment]
> E2E is available in version 2020.12.2 and later. Then you should see the point "End-to-End Encryption" at the end of the security section.

thanks for replying promptly!
I am running 2020.12.2 https://i.imgur.com/5uYGnsd.png
but there's no "End-to-End Encryption" at the end of the Security section, as you can see here: https://i.imgur.com/vsYyHKW.png
Maybe theer's some dependency I've not installed ?

**Comment by marius-wieschollek** [comment]
I checked this, but i can't reproduce the issue. In 2020.12, e2e had a feature switch which determines if the feature is available or not. If you open the passwords app, it should check [this file](https://raw.githubusercontent.com/wiki/marius-wieschollek/passwords/Users/_files/deferred-activation.json) from the user handbook and show the option if it's enabled.

If that does not work for some reason, you can try updating to 2021.3 where the feature is enabled by default.
